# wlp2s0

MASTER_NODES = 1
WORKER_NODES = 2

NETWORK_IP = "192.168.56."
# MASTER_IP = "192.168.56.1"

Vagrant.configure("2") do |config|
	config.vm.box = "generic/debian12"
	config.vm.box_version = "4.3.12"
	config.vm.provider "virtualbox" do |vb|
		vb.memory = "2048"
		vb.cpus = 2
	end

	config.vm.synced_folder "../", "/vagrant"

	config.vm.provision "shell", inline: <<-SHELL
		apt-get update
		apt-get install -y vim

		sed -i.bak 's/^#PubkeyAuthentication yes/PubkeyAuthentication yes/' "/etc/ssh/sshd_config"
		ssh-keygen -t rsa -b 4096 -f "$HOME/.ssh/id_rsa" -N "" 
		systemctl restart sshd
		echo -e " \n " | passwd
		
		apt-get install sshpass
		echo 'cd /vagrant/dev' >> /root/.profile
	SHELL

	(1..WORKER_NODES).each do |i|
		config.vm.define "node#{i}" do |node|
			node.vm.synced_folder "../", "/vagrant"
			node.vm.hostname = "node#{i}"
			node.vm.network :private_network, ip: NETWORK_IP + "#{10 + i}"
		end
	end

	config.vm.define "master" do |master|
		master.vm.hostname = "master"
		master.vm.network "private_network", ip: "192.168.56.1"
	
		master.vm.provision "shell", inline: <<-SHELL
			apt-get update
			apt-get install -y ansible
			echo [defaults] > ~/.ansible.cfg
			echo "host_key_checking = False" >> ~/.ansible.cfg

			sshpass -p " " ssh-copy-id -o StrictHostKeyChecking=no root@192.168.56.1
			for (( i=11; i<=12; i++ )) do
				sshpass -p " " ssh-copy-id -o StrictHostKeyChecking=no root@192.168.56.$i
				ssh root@192.168.56.$i "sshpass -p ' ' ssh-copy-id -o StrictHostKeyChecking=no root@192.168.56.1"
			done
		SHELL
	end

end

# kubectl cp laplacien_3d.py default/<some-pod>:/data
# mpirun --allow-run-as-root -np 2 python laplacien_3d.py

# 192.168.56.1	master
# 192.168.56.11	node1
# 192.168.56.12	node2