Vagrant.configure("2") do |config|
	config.vm.box = "generic/debian12"
	config.vm.box_version = "4.3.12"
	config.vm.provider "virtualbox" do |vb|
		vb.memory = "2048"
		vb.cpus = 2
	end

	config.vm.synced_folder "../", "/vagrant"

	config.vm.provision "shell", inline: <<-SHELL
		apt-get update
		apt-get install -y vim

		sed -i.bak 's/^#PubkeyAuthentication yes/PubkeyAuthentication yes/' "/etc/ssh/sshd_config"
		cp -fr /vagrant/dev/.ssh/ ~/
		systemctl restart sshd

		echo 'cd /vagrant/dev' >> /root/.profile
	SHELL
	
	config.vm.define "master" do |master|
		master.vm.hostname = "master"
		master.vm.network "private_network", ip: "192.168.56.10"
	end

	config.vm.define "node" do |node|
		node.vm.synced_folder "../", "/vagrant"
		node.vm.hostname = "node"
		config.vm.network "public_network", disabled: true
		node.vm.network "private_network", ip: "192.168.56.11"
	end

end

